// Generated by LiveScript 1.4.0
(function(){
  var $, fullcalendar, _, h, ical, env, slice$ = [].slice;
  $ = require('jquery');
  fullcalendar = require('fullcalendar');
  _ = require('underscore');
  h = require('helpers');
  ical = require('ical');
  env = window.env = {};
  $(document).ready(function(){
    var calendar, _colors, color;
    calendar = env.calendar = function(){
      var args, el;
      args = slice$.call(arguments);
      el = $('#calendar');
      return el.fullCalendar.apply(el, args);
    };
    calendar({});
    _colors = ['#B35982', '#9BC362', '#4F9D66', '#D4796A'];
    color = window.color = function(){
      var ret;
      ret = _colors.shift();
      _colors.push(ret);
      return ret;
    };
    return $('#files').change(function(evt){
      var files;
      files = evt.target.files;
      return _.each(files, function(file){
        var reader;
        if (file.type !== "text/calendar") {
          return console.error("wrong file type: " + file.type);
        }
        reader = new FileReader;
        reader.onload = function(e){
          var ics, events;
          ics = ical.parseICS(e.target.result);
          events = _.map(_.values(_.omit(ics, 'prodid')), function(data){
            return {
              title: data.summary,
              allDay: true,
              start: data.start,
              end: data.end
            };
          });
          return calendar('addEventSource', {
            events: events,
            color: color()
          });
        };
        return reader.readAsText(file);
      });
    });
  });
}).call(this);
