// Generated by LiveScript 1.4.0
(function(){
  var async, _, h, $;
  async = require('async');
  _ = require('underscore');
  h = require('helpers');
  $ = require('jquery');
  console.log('hi there');
}).call(this);
